import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'package:signals_flutter/signals_flutter.dart';
import 'package:vocabulary_table_app/controller/vocabulary_controller.dart';
import 'package:vocabulary_table_app/models/vocabulary_item.dart';
import 'package:vocabulary_table_app/widgets/vocabulary_table_app.dart';

void main(List<String> args) {
  SignalsObserver.instance = null;

  WidgetsFlutterBinding.ensureInitialized();

  setUpDependencies();

  runApp(
    MaterialApp(
      home: VocabularyTableApp(),
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.orangeAccent,
          brightness: .light,
        ),
      ),
      debugShowCheckedModeBanner: false,
    ),
  );
}

void setUpDependencies() {
  GetIt.I.registerLazySingleton(
    () => VocabularyController(vocabularyItems: _vocabularies),
  );
}

/// 200 vocabulary items for testing, a typical chapter size.
final _vocabularies = [
  VocabularyItem(termA: 'apple', termB: 'Apfel', comment: 'süß'),
  VocabularyItem(termA: 'house', termB: 'Haus', comment: 'sicher'),
  VocabularyItem(termA: 'book', termB: 'Buch', comment: 'spannend'),
  VocabularyItem(termA: 'car', termB: 'Auto', comment: 'schnell'),
  VocabularyItem(termA: 'tree', termB: 'Baum', comment: 'grün'),
  VocabularyItem(termA: 'dog', termB: 'Hund', comment: 'treu'),
  VocabularyItem(termA: 'cat', termB: 'Katze', comment: 'eigensinnig'),
  VocabularyItem(termA: 'river', termB: 'Fluss', comment: 'tief'),
  VocabularyItem(
    termA:
        'Hier sollte auch einmal ein ganzer Satz stehen, damit man sieht, wie die Tabelle mit mehreren Zeilen umgeht.',
    termB:
        'There should also be a complete sentence here so you can see how the table handles multiple rows.',
    comment: 'mehrere Zeilen',
  ),
  VocabularyItem(termA: 'mountain', termB: 'Berg', comment: 'hoch'),
  VocabularyItem(termA: 'sun', termB: 'Sonne', comment: 'heiß'),
  VocabularyItem(termA: 'moon', termB: 'Mond', comment: 'hell'),
  VocabularyItem(termA: 'star', termB: 'Stern', comment: 'weit weg'),
  VocabularyItem(termA: 'child', termB: 'Kind', comment: 'verspielt'),
  VocabularyItem(termA: 'friend', termB: 'Freund', comment: 'wichtig'),
  VocabularyItem(termA: 'city', termB: 'Stadt', comment: 'laut'),
  VocabularyItem(termA: 'street', termB: 'Straße', comment: 'lang'),
  VocabularyItem(termA: 'window', termB: 'Fenster', comment: 'sauber'),
  VocabularyItem(termA: 'door', termB: 'Tür', comment: 'geschlossen'),
  VocabularyItem(termA: 'table', termB: 'Tisch', comment: 'hölzern'),
  VocabularyItem(termA: 'chair', termB: 'Stuhl', comment: 'bequem'),
  VocabularyItem(termA: 'computer', termB: 'Computer', comment: 'nützlich'),
  VocabularyItem(termA: 'phone', termB: 'Telefon', comment: 'mobil'),
  VocabularyItem(termA: 'water', termB: 'Wasser', comment: 'erfrischend'),
  VocabularyItem(termA: 'bread', termB: 'Brot', comment: 'frisch'),
  VocabularyItem(termA: 'milk', termB: 'Milch', comment: 'kalt'),
  VocabularyItem(termA: 'coffee', termB: 'Kaffee', comment: 'stark'),
  VocabularyItem(termA: 'tea', termB: 'Tee', comment: 'beruhigend'),
  VocabularyItem(termA: 'sea', termB: 'Meer', comment: 'blau'),
  VocabularyItem(termA: 'beach', termB: 'Strand', comment: 'sandig'),
  VocabularyItem(termA: 'cloud', termB: 'Wolke', comment: 'weiß'),
  VocabularyItem(termA: 'rain', termB: 'Regen', comment: 'nass'),
  VocabularyItem(termA: 'snow', termB: 'Schnee', comment: 'kalt'),
  VocabularyItem(termA: 'wind', termB: 'Wind', comment: 'stürmisch'),
  VocabularyItem(termA: 'fire', termB: 'Feuer', comment: 'gefährlich'),
  VocabularyItem(termA: 'earth', termB: 'Erde', comment: 'fruchtbar'),
  VocabularyItem(termA: 'bird', termB: 'Vogel', comment: 'fliegend'),
  VocabularyItem(termA: 'fish', termB: 'Fisch', comment: 'stumm'),
  VocabularyItem(termA: 'flower', termB: 'Blume', comment: 'duftend'),
  VocabularyItem(termA: 'garden', termB: 'Garten', comment: 'bunt'),
  VocabularyItem(termA: 'forest', termB: 'Wald', comment: 'dunkel'),
  VocabularyItem(termA: 'sky', termB: 'Himmel', comment: 'klar'),
  VocabularyItem(termA: 'key', termB: 'Schlüssel', comment: 'klein'),
  VocabularyItem(termA: 'bag', termB: 'Tasche', comment: 'schwer'),
  VocabularyItem(termA: 'clock', termB: 'Uhr', comment: 'pünktlich'),
  VocabularyItem(termA: 'money', termB: 'Geld', comment: 'wichtig'),
  VocabularyItem(termA: 'paper', termB: 'Papier', comment: 'beschrieben'),
  VocabularyItem(termA: 'pen', termB: 'Stift', comment: 'blau'),
  VocabularyItem(termA: 'picture', termB: 'Bild', comment: 'schön'),
  VocabularyItem(termA: 'music', termB: 'Musik', comment: 'laut'),
  VocabularyItem(termA: 'game', termB: 'Spiel', comment: 'lustig'),
  VocabularyItem(termA: 'time', termB: 'Zeit', comment: 'kostbar'),
  VocabularyItem(termA: 'life', termB: 'Leben', comment: 'aufregend'),
  VocabularyItem(termA: 'love', termB: 'Liebe', comment: 'unendlich'),
  VocabularyItem(termA: 'heart', termB: 'Herz', comment: 'schlagend'),
  VocabularyItem(termA: 'light', termB: 'Licht', comment: 'hell'),
  VocabularyItem(termA: 'shadow', termB: 'Schatten', comment: 'kühl'),
  VocabularyItem(termA: 'dream', termB: 'Traum', comment: 'schön'),
  VocabularyItem(termA: 'night', termB: 'Nacht', comment: 'dunkel'),
  VocabularyItem(termA: 'day', termB: 'Tag', comment: 'sonnig'),
  VocabularyItem(termA: 'summer', termB: 'Sommer', comment: 'warm'),
  VocabularyItem(termA: 'winter', termB: 'Winter', comment: 'frostig'),
  VocabularyItem(termA: 'spring', termB: 'Frühling', comment: 'blühend'),
  VocabularyItem(termA: 'autumn', termB: 'Herbst', comment: 'stürmisch'),
  VocabularyItem(
    termA:
        'Learning a new language opens up many new opportunities for your future.',
    termB:
        'Eine neue Sprache zu lernen eröffnet viele neue Möglichkeiten für deine Zukunft.',
    comment: 'langer Beispielsatz',
  ),
  VocabularyItem(termA: 'school', termB: 'Schule', comment: 'lehrreich'),
  VocabularyItem(termA: 'teacher', termB: 'Lehrer', comment: 'geduldig'),
  VocabularyItem(termA: 'student', termB: 'Schüler', comment: 'neugierig'),
  VocabularyItem(termA: 'work', termB: 'Arbeit', comment: 'anstrengend'),
  VocabularyItem(termA: 'success', termB: 'Erfolg', comment: 'groß'),
  VocabularyItem(termA: 'goal', termB: 'Ziel', comment: 'wichtig'),
  VocabularyItem(termA: 'journey', termB: 'Reise', comment: 'unvergesslich'),
  VocabularyItem(termA: 'ship', termB: 'Schiff', comment: 'riesig'),
  VocabularyItem(termA: 'airplane', termB: 'Flugzeug', comment: 'schnell'),
  VocabularyItem(termA: 'train', termB: 'Zug', comment: 'pünktlich'),
  VocabularyItem(
    termA: 'bicycle',
    termB: 'Fahrrad',
    comment: 'umweltfreundlich',
  ),
  VocabularyItem(termA: 'island', termB: 'Insel', comment: 'einsam'),
  VocabularyItem(
    termA: 'mountain top',
    termB: 'Gipfel',
    comment: 'atemberaubend',
  ),
  VocabularyItem(termA: 'stone', termB: 'Stein', comment: 'hart'),
  VocabularyItem(termA: 'bridge', termB: 'Brücke', comment: 'stabil'),
  VocabularyItem(termA: 'mirror', termB: 'Spiegel', comment: 'glänzend'),
  VocabularyItem(termA: 'glass', termB: 'Glas', comment: 'zerbrechlich'),
  VocabularyItem(termA: 'plate', termB: 'Teller', comment: 'voll'),
  VocabularyItem(termA: 'spoon', termB: 'Löffel', comment: 'silbern'),
  VocabularyItem(termA: 'knife', termB: 'Messer', comment: 'scharf'),
  VocabularyItem(termA: 'fork', termB: 'Gabel', comment: 'spitz'),
  VocabularyItem(termA: 'food', termB: 'Essen', comment: 'lecker'),
  VocabularyItem(termA: 'fruit', termB: 'Obst', comment: 'gesund'),
  VocabularyItem(termA: 'vegetable', termB: 'Gemüse', comment: 'frisch'),
  VocabularyItem(termA: 'cheese', termB: 'Käse', comment: 'würzig'),
  VocabularyItem(termA: 'cake', termB: 'Kuchen', comment: 'süß'),
  VocabularyItem(
    termA: 'Can you please tell me the way to the nearest train station?',
    termB: 'Können Sie mir bitte den Weg zum nächsten Bahnhof beschreiben?',
    comment: 'Fragesatz im Test',
  ),
  VocabularyItem(termA: 'hat', termB: 'Hut', comment: 'schick'),
  VocabularyItem(termA: 'shoes', termB: 'Schuhe', comment: 'bequem'),
  VocabularyItem(termA: 'coat', termB: 'Mantel', comment: 'warm'),
  VocabularyItem(termA: 'color', termB: 'Farbe', comment: 'bunt'),
  VocabularyItem(termA: 'voice', termB: 'Stimme', comment: 'angenehm'),
  VocabularyItem(termA: 'smile', termB: 'Lächeln', comment: 'freundlich'),
  VocabularyItem(termA: 'laugh', termB: 'Lachen', comment: 'ansteckend'),
  VocabularyItem(termA: 'tear', termB: 'Träne', comment: 'traurig'),
  VocabularyItem(termA: 'world', termB: 'Welt', comment: 'riesig'),
  VocabularyItem(termA: 'history', termB: 'Geschichte', comment: 'vergangen'),
  VocabularyItem(termA: 'future', termB: 'Zukunft', comment: 'ungewiss'),
  VocabularyItem(termA: 'present', termB: 'Gegenwart', comment: 'wichtig'),
  VocabularyItem(termA: 'art', termB: 'Kunst', comment: 'kreativ'),
  VocabularyItem(termA: 'science', termB: 'Wissenschaft', comment: 'logisch'),
  VocabularyItem(termA: 'nature', termB: 'Natur', comment: 'wunderbar'),
  VocabularyItem(termA: 'health', termB: 'Gesundheit', comment: 'wertvoll'),
  VocabularyItem(termA: 'peace', termB: 'Frieden', comment: 'notwendig'),
  VocabularyItem(termA: 'freedom', termB: 'Freiheit', comment: 'kostbar'),
  VocabularyItem(termA: 'knowledge', termB: 'Wissen', comment: 'machtvoll'),
  VocabularyItem(termA: 'wisdom', termB: 'Weisheit', comment: 'alt'),
  VocabularyItem(termA: 'truth', termB: 'Wahrheit', comment: 'klar'),
  VocabularyItem(termA: 'honesty', termB: 'Ehrlichkeit', comment: 'selten'),
  VocabularyItem(termA: 'courage', termB: 'Mut', comment: 'stark'),
  VocabularyItem(termA: 'patience', termB: 'Geduld', comment: 'schwer'),
  VocabularyItem(
    termA: 'An investment in knowledge always pays the best interest.',
    termB: 'Eine Investition in Wissen bringt immer noch die besten Zinsen.',
    comment: 'Sprichwort / Zitat',
  ),
  VocabularyItem(termA: 'ocean', termB: 'Ozean', comment: 'unendlich'),
  VocabularyItem(termA: 'desert', termB: 'Wüste', comment: 'trocken'),
  VocabularyItem(termA: 'jungle', termB: 'Dschungel', comment: 'wild'),
  VocabularyItem(termA: 'island', termB: 'Insel', comment: 'abgelegen'),
  VocabularyItem(termA: 'valley', termB: 'Tal', comment: 'grün'),
  VocabularyItem(termA: 'cave', termB: 'Höhle', comment: 'dunkel'),
  VocabularyItem(termA: 'waterfall', termB: 'Wasserfall', comment: 'laut'),
  VocabularyItem(termA: 'lake', termB: 'See', comment: 'ruhig'),
  VocabularyItem(termA: 'ice', termB: 'Eis', comment: 'glatt'),
  VocabularyItem(termA: 'gold', termB: 'Gold', comment: 'teuer'),
  VocabularyItem(termA: 'silver', termB: 'Silber', comment: 'glänzend'),
  VocabularyItem(termA: 'iron', termB: 'Eisen', comment: 'schwer'),
  VocabularyItem(termA: 'diamond', termB: 'Diamant', comment: 'hart'),
  VocabularyItem(termA: 'wood', termB: 'Holz', comment: 'warm'),
  VocabularyItem(termA: 'experience', termB: 'Erfahrung', comment: 'hilfreich'),
  VocabularyItem(termA: 'mistake', termB: 'Fehler', comment: 'lehrreich'),
  VocabularyItem(termA: 'solution', termB: 'Lösung', comment: 'genial'),
  VocabularyItem(termA: 'problem', termB: 'Problem', comment: 'komplex'),
  VocabularyItem(termA: 'question', termB: 'Frage', comment: 'offen'),
  VocabularyItem(termA: 'answer', termB: 'Antwort', comment: 'richtig'),
  VocabularyItem(termA: 'idea', termB: 'Idee', comment: 'kreativ'),
  VocabularyItem(termA: 'thought', termB: 'Gedanke', comment: 'flüchtig'),
  VocabularyItem(termA: 'memory', termB: 'Erinnerung', comment: 'schön'),
  VocabularyItem(termA: 'hope', termB: 'Hoffnung', comment: 'unsterblich'),
  VocabularyItem(
    termA:
        'The developer spent the entire night tracking down a single, elusive bug in the production code.',
    termB:
        'Der Entwickler verbrachte die ganze Nacht damit, einen einzelnen, schwer fassbaren Fehler im Produktionscode zu finden.',
    comment: 'technischer Beispielsatz',
  ),
  VocabularyItem(termA: 'family', termB: 'Familie', comment: 'geborgen'),
  VocabularyItem(termA: 'brother', termB: 'Bruder', comment: 'hilfsbereit'),
  VocabularyItem(termA: 'sister', termB: 'Schwester', comment: 'fürsorglich'),
  VocabularyItem(termA: 'parents', termB: 'Eltern', comment: 'liebevoll'),
  VocabularyItem(termA: 'neighbor', termB: 'Nachbar', comment: 'nett'),
  VocabularyItem(termA: 'stranger', termB: 'Fremder', comment: 'unbekannt'),
  VocabularyItem(termA: 'guest', termB: 'Gast', comment: 'willkommen'),
  VocabularyItem(termA: 'community', termB: 'Gemeinschaft', comment: 'stark'),
  VocabularyItem(
    termA: 'society',
    termB: 'Gesellschaft',
    comment: 'vielfältig',
  ),
  VocabularyItem(termA: 'culture', termB: 'Kultur', comment: 'interessant'),
  VocabularyItem(termA: 'language', termB: 'Sprache', comment: 'lebendig'),
  VocabularyItem(termA: 'word', termB: 'Wort', comment: 'mächtig'),
  VocabularyItem(termA: 'sentence', termB: 'Satz', comment: 'vollständig'),
  VocabularyItem(termA: 'meaning', termB: 'Bedeutung', comment: 'tief'),
  VocabularyItem(termA: 'secret', termB: 'Geheimnis', comment: 'verborgen'),
  VocabularyItem(termA: 'shadow', termB: 'Schatten', comment: 'dunkel'),
  VocabularyItem(termA: 'silence', termB: 'Stille', comment: 'angenehm'),
  VocabularyItem(termA: 'sound', termB: 'Geräusch', comment: 'leise'),
  VocabularyItem(termA: 'noise', termB: 'Lärm', comment: 'nervig'),
  VocabularyItem(
    termA:
        'Could you please point out where the historical museum is located on this map?',
    termB:
        'Könnten Sie mir bitte auf dieser Karte zeigen, wo sich das historische Museum befindet?',
    comment: 'Wegbeschreibung',
  ),
  VocabularyItem(termA: 'market', termB: 'Markt', comment: 'belebt'),
  VocabularyItem(termA: 'shop', termB: 'Geschäft', comment: 'voll'),
  VocabularyItem(termA: 'price', termB: 'Preis', comment: 'fair'),
  VocabularyItem(termA: 'cost', termB: 'Kosten', comment: 'hoch'),
  VocabularyItem(termA: 'bill', termB: 'Rechnung', comment: 'bezahlt'),
  VocabularyItem(termA: 'tax', termB: 'Steuer', comment: 'kompliziert'),
  VocabularyItem(termA: 'business', termB: 'Geschäft', comment: 'erfolgreich'),
  VocabularyItem(termA: 'company', termB: 'Unternehmen', comment: 'modern'),
  VocabularyItem(termA: 'office', termB: 'Büro', comment: 'hell'),
  VocabularyItem(termA: 'meeting', termB: 'Besprechung', comment: 'produktiv'),
  VocabularyItem(termA: 'project', termB: 'Projekt', comment: 'ambitioniert'),
  VocabularyItem(termA: 'team', termB: 'Team', comment: 'kollegial'),
  VocabularyItem(termA: 'task', termB: 'Aufgabe', comment: 'schwierig'),
  VocabularyItem(termA: 'schedule', termB: 'Zeitplan', comment: 'strikt'),
  VocabularyItem(termA: 'deadline', termB: 'Frist', comment: 'nahend'),
  VocabularyItem(
    termA:
        'The more you practice, the more fluent your conversation will naturally become over time.',
    termB:
        'Je mehr du übst, desto fließender wird deine Konversation im Laufe der Zeit ganz natürlich werden.',
    comment: 'Lern-Motivation',
  ),
  VocabularyItem(termA: 'kitchen', termB: 'Küche', comment: 'sauber'),
  VocabularyItem(termA: 'bedroom', termB: 'Schlafzimmer', comment: 'gemütlich'),
  VocabularyItem(termA: 'bathroom', termB: 'Badezimmer', comment: 'gefliest'),
  VocabularyItem(termA: 'roof', termB: 'Dach', comment: 'hoch'),
  VocabularyItem(termA: 'floor', termB: 'Boden', comment: 'gewischt'),
  VocabularyItem(termA: 'wall', termB: 'Wand', comment: 'weiß'),
  VocabularyItem(termA: 'staircase', termB: 'Treppe', comment: 'steil'),
  VocabularyItem(termA: 'balcony', termB: 'Balkon', comment: 'sonnig'),
  VocabularyItem(termA: 'furniture', termB: 'Möbel', comment: 'schwer'),
  VocabularyItem(termA: 'bed', termB: 'Bett', comment: 'weich'),
  VocabularyItem(termA: 'pillow', termB: 'Kissen', comment: 'bequem'),
  VocabularyItem(termA: 'blanket', termB: 'Decke', comment: 'warm'),
  VocabularyItem(termA: 'curtain', termB: 'Vorhang', comment: 'blickdicht'),
  VocabularyItem(termA: 'lamp', termB: 'Lampe', comment: 'leuchtend'),
  VocabularyItem(termA: 'box', termB: 'Kiste', comment: 'eckig'),
  VocabularyItem(termA: 'bottle', termB: 'Flasche', comment: 'leer'),
  VocabularyItem(termA: 'cup', termB: 'Tasse', comment: 'heiß'),
  VocabularyItem(termA: 'taste', termB: 'Geschmack', comment: 'gut'),
  VocabularyItem(termA: 'smell', termB: 'Geruch', comment: 'intensiv'),
  VocabularyItem(termA: 'touch', termB: 'Berührung', comment: 'sanft'),
  VocabularyItem(termA: 'view', termB: 'Aussicht', comment: 'schön'),
  VocabularyItem(termA: 'weather', termB: 'Wetter', comment: 'wechselhaft'),
  VocabularyItem(termA: 'climate', termB: 'Klima', comment: 'mild'),
  VocabularyItem(
    termA:
        'Please make sure to save all your current changes before closing the application window.',
    termB:
        'Bitte stellen Sie sicher, dass Sie alle aktuellen Änderungen speichern, bevor Sie das Anwendungsfenster schließen.',
    comment: 'Software-Hinweis',
  ),
];
